### ISSUE TITLE
httpOnly = true is not enabling the cookie to be httpOnly and maxAge is not working too

### ISSUE THREAD

**Issue by divyabiyani** [bukinoshita/react-cookies#10]
I am currently saving a cookie with the following options. But maxAge is not working.
{
        'path': params.path ? params.path : '/',
        'maxAge': params.maxAge ? params.maxAge : 3600,
        'domain': params.domain ? params.domain : 'http://localhost:8000',
        'httpOnly': params.httpOnly ? params.httpOnly : true,
        'secure': params.secure ? params.secure: false
}

**Comment by bukinoshita** [comment]
Can you share which browser are you testing?

**Comment by bukinoshita** [comment]
adding this to v1 release, will investigate!

**Comment by bukinoshita** [comment]
https://github.com/bukinoshita/react-cookies/releases/tag/v0.1.2-beta.0
