### ISSUE TITLE
maxAge not working on IE11

### ISSUE THREAD

**Issue by kimmiekim** [bukinoshita/react-cookies#11]
I've set MaxAge to 20 years in order to save the cookies in persistent. 
it's working fine on both Chrome and firefox, but not working on IE11.
Cookies get deleted when browser closes. 

 `cookies.set('checkedItems', JSON.stringify(checkedItemsArr), {path: '/', maxAge: 	630720000 })`

Is this not IE compatible?

**Comment by bukinoshita** [comment]
adding this to v1 release, will investigate!

**Comment by bukinoshita** [comment]
https://github.com/bukinoshita/react-cookies/releases/tag/v0.1.2-beta.0
