### ISSUE TITLE
expires is not working!

### ISSUE THREAD

**Issue by sameerhexagon** [bukinoshita/react-cookies#12]
Hello,
I am trying to set cookie with expires option but it is not working.

`let currentDate = new Date();`
`let expireDate = new Date(currentDate.getFullYear(), currentDate.getMonth(),currentDate.getDate()+1), 0,0,0);`
`console.log(expireDate);`
`console.log(typeof(expireDate));`
`return cookie.save(key, value, { path: "/", expires: expireDate});`

console shows right date and type is object.
but it is not setting any cookie. Without expires it is working fine.
This is the behaviour in chrome, in firefox it is working fine.

**Comment by noecs** [comment]
I also encountered the effective time (seconds) that my backend returns to the frontend token.
```
      const expires = new Date();
      expires.setDate(Date.now() + action.payload.expires_in * 1000);

      cookie.save('token_type', action.payload.token_type, {
        expires
      });
```

**Comment by bukinoshita** [comment]
adding this to v1 release, will investigate!

**Comment by bukinoshita** [comment]
https://github.com/bukinoshita/react-cookies/releases/tag/v0.1.2-beta.0

**Comment by salientknight** [comment]
I came across this today and solved it as follows

```
const expires = new Date();
    expires.setDate(100);
```
