### ISSUE TITLE
how to reset maxAge ?

### ISSUE THREAD

**Issue by taoxueweilong** [bukinoshita/react-cookies#7]

**Comment by bukinoshita** [comment]
what do you mean by `reset maxAge`?

**Comment by taoxueweilong** [comment]
I want to use this cookie implement the login timeout function, and if the user operate the system within the valid period, reset the expiration time of the cookie, I kown the method by queringcookies and resave them to reset, but is there a way to reset the time directly?

**Comment by bukinoshita** [comment]
No, you have to do that on your project. Maybe the best option is to resave the cookie with a new maxAge

**Comment by taoxueweilong** [comment]
ok, thanks
