### ISSUE TITLE
Cookie persist

### ISSUE THREAD

**Issue by bthomasazap** [bukinoshita/react-cookies#9]
Hi,

I'm using chrome with react. And after saveCookie, when i close the browser and restart the browser my cookie is not persist.

`var base64 = btoa(newSplittersPositionString); // save the data to base64
 cookie.save(Constants.COOKIE_SPLITTER, base64);`

Can you help me?

thanks

**Comment by bukinoshita** [comment]
Here's a quick example on how to use `react-cookies` with `react`.

https://github.com/bukinoshita/react-cookies-example

Can you also test if this only happens with Chrome? Which version of Chrome?

**Comment by bthomasazap** [comment]
It’s look, it’s works if i add `expires: now, path: '/'`
But when I give not option is not mean “never expire”?

De : Bu Kinoshita [mailto:notifications@github.com]
Envoyé : Friday, February 2, 2018 2:11 PM
À : bukinoshita/react-cookies <react-cookies@noreply.github.com>
Cc : Benjamin THOMAS <bthomas@azap.com>; Author <author@noreply.github.com>
Objet : Re: [bukinoshita/react-cookies] Cookie persist (#9)


Here's a quick example on how to use react-cookies with react.

https://github.com/bukinoshita/react-cookies-example

Can you also test if this only happens with Chrome? Which version of Chrome?

**Comment by bthomasazap** [comment]
It’s look, it’s works if i add
`{
        expires: now,
        path: '/'
    }`

But when I give not option is not mean “never expire”?

**Comment by bukinoshita** [comment]
I'm glad it's working! 🎉 

It does not mean that.

> ;expires=date-in-GMTString-format If neither `expires` nor `max-age` specified it will expire at the end of session.

[Developer Mozilla Web API cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)
